# Generated by Django 3.1.5 on 2024-04-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_cms', '0002_student_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_grades',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
